version: '3.4'

services:
  # 用来保存域名相关信息的 Redis
  redis-ddns:
    image: redis:alpine
    container_name: ali-ddns-redis-ddns
    # 设置 Redis 的密码，下面记得主服务中填写对应的密码
    command: redis-server --port 6380 --requirepass redis-ddns-password
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/ddns/data:/data
      - ./redis/ddns/logs:/logs
    networks:
      net:
        aliases:
          - redis-ddns

  # 用来保存 session 信息的 Redis
  redis-session:
    image: redis:alpine
    container_name: ali-ddns-redis-session
    # 设置 Redis 的密码，下面记得主服务中填写对应的密码
    command: redis-server --port 6381 --requirepass redis-session-password
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/session/data:/data
      - ./redis/session/logs:/logs
    networks:
      net:
        aliases:
          - redis-session

  # 主服务
  ali-ddns-server-service:
    # 阿里云仓库:  registry.cn-shenzhen.aliyuncs.com/hominsu/ali-ddns-server-service:latest
    # GHCR:      ghcr.io/hominsu/ali-ddns-server-service:latest
    # DockerHub: hominsu/ali-ddns-server-service:latest
    image: hominsu/ali-ddns-server-service:latest
    container_name: ali-ddns-server-service
    #    build:
    #      context: .
    #      dockerfile: ./Dockerfile
    depends_on:
      - redis-session
      - redis-ddns
    restart: always
    environment:
      # 设置时区，不然 logs 的时间不对
      TZ: "Asia/Shanghai" # 时区

      GIN_MODE: "release"

      # 设置阿里云的 AK，建议使用 RAM 用户，只分配 AliyunDNSFullAccess 权限
      ALIDDNSSERVER_ACCESSKEY_ID: "*"            # 阿里云 AK ID
      ALIDDNSSERVER_ACCESSKEY_SECRET: "*"  # 阿里云 AK SECRET

      ALIDDNSSERVER_BASIC_ENDPOINT: "alidns.cn-shenzhen.aliyuncs.com"   # 阿里云服务地址
      ALIDDNSSERVER_BASIC_INTERFACE_PORT: "50001"                             # WEB 服务监听端口
      ALIDDNSSERVER_BASIC_DOMAIN_GRPC_NETWORK: "tcp"                    # RPC 协议
      ALIDDNSSERVER_BASIC_DOMAIN_GRPC_PORT: "50002"                     # RPC 服务端口
      ALIDDNSSERVER_BASIC_INTERFACE_GRPC_NETWORK: "tcp"                 # RPC 协议
      ALIDDNSSERVER_BASIC_INTERFACE_GRPC_PORT: "50003"                  # RPC 服务端口

      # 保存域名相关信息的 Redis，要改的只有密码，和上面设置的密码相同
      ALIDDNSSERVER_DOMAIN_RECORD_REDIS_ADDR: "redis-ddns"              # 保存域名信息的 Redis 地址
      ALIDDNSSERVER_DOMAIN_RECORD_REDIS_PORT: "6380"                    # 保存域名信息的 Redis 端口
      ALIDDNSSERVER_DOMAIN_RECORD_REDIS_PASSWORD: "redis-ddns-password" # 保存域名信息的 Redis 密码
      ALIDDNSSERVER_DOMAIN_RECORD_REDIS_DB: "1"                         # 保存域名信息的 Redis 数据库

      ALIDDNSCLIENT_OPTION_JWT_TOKEN: "www.hauhau.cn"
      ALIDDNSCLIENT_OPTION_TTL: "3600"                                              # 每隔多少秒向服务端获取更新信息
      ALIDDNSCLIENT_OPTION_DELAY_CHECK_CRON: "CRON_TZ=Asia/Shanghai 1/10 2-4 * * *" # 每天的 2-4 点的 1m 开始，每 10m 执行一次

    volumes:
      - ./cert:/cert
    ports:
      - "50001:50001"
      - "50002:50002"
    networks:
      - net

networks:
  net:
    driver: bridge