// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Ali-DDNS/app/domain_check/internal/domain_check/data"
	"Ali-DDNS/app/domain_check/internal/domain_check/server"
	"Ali-DDNS/app/domain_check/internal/domain_check/service"
)

// Injectors from wire.go:

// initApp init ddns client application.
func initApp() (*App, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	domainCheckService := service.NewDomainCheckService(dataData)
	cron, err := server.NewCronServer(domainCheckService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(cron)
	return app, func() {
		cleanup()
	}, nil
}
