// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Ali-DDNS/app/domain_service/internal/domain_task/biz"
	"Ali-DDNS/app/domain_service/internal/domain_task/data"
	"Ali-DDNS/app/domain_service/internal/domain_task/server"
	"Ali-DDNS/app/domain_service/internal/domain_task/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp() (*App, func(), error) {
	client := data.NewRedisClient()
	dataData, cleanup, err := data.NewData(client)
	if err != nil {
		return nil, nil, err
	}
	delayCheckRepo := data.NewDelayCheckRepo(dataData)
	delayCheckUsecase := biz.NewDelayCheckUsecase(delayCheckRepo)
	domainRecordRepo := data.NewDomainRecordRepo(dataData)
	domainRecordUsecase := biz.NewDomainRecordUsecase(domainRecordRepo)
	domainUserRepo := data.NewDomainUserRepo(dataData)
	domainUserUsecase := biz.NewDomainUserUsecase(domainUserRepo)
	domainTaskService := service.NewDomainTaskService(delayCheckUsecase, domainRecordUsecase, domainUserUsecase)
	grpcServer := server.NewGRPCServer(domainTaskService)
	engine := server.NewGinServer(domainTaskService)
	app := newApp(grpcServer, engine)
	return app, func() {
		cleanup()
	}, nil
}
