name: CodeQL Analysis

on:
  push:
    branches: [ master, dev ]
    tags: [ '*.*.*' ]
  workflow_dispatch:

jobs:
  CodeQL-Analysis:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Build
        run: |
          go get -d -v ./...
          make init
          make all
          make build

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.build_type }} > CTest-${{ matrix.build_type }}-${{ matrix.os }}.log

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1


